### ISSUE TITLE
Panning and Zooming in ForceLayout

### ISSUE THREAD

**Issue by dylan-plummer** [kai0masanari/Forcelayout#1]
I am using this library to visualize a network graph with ~150 nodes.  It looks great but I need some way to adjust the actual view of the graph via panning around the view and zooming in since the graph is too large to fit on a phone screen without getting extremely cluttered.

First I attempted to build my own solution using ScrollViews with the ForceLayout as the child but this prevented the graph from being displayed at all.  Next I tried using this libary: [https://github.com/natario1/ZoomLayout](ZoomLayout) with ForceLayout as child but again, similar problems.

Is there functionality within this layout to adjust the view?  I have no issues designing the UI for adjusting these values in my app, I simply need a way to change the center of the view and possibly the scale of the view for panning and zooming.

Thank you for any help.

**Comment by kai0masanari** [comment]
Thank you for your reviewing my code.
I'll try to remake this program as soon as possible.
Don't have too much expectation for my renewal program.

**Comment by kai0masanari** [comment]
Hi, dylan.
This issue has been resolved in version [1.1.0](https://bintray.com/kai0masanari/maven/forcelayout/1.1.0). Prease confirm.
